### ISSUE TITLE
Missing password from LDAP warning shall not be seen as important log

### ISSUE THREAD

**Issue by Berbe** [piwik/plugin-LoginLdap#204]
As https://github.com/matomo-org/plugin-LoginLdap/blob/aea78502d4f37ef89676bff8dedf18adafadc940/LdapInterop/UserMapper.php#L145 points it out, passwords from LDAP are not used in Matomo. Not exposing passwords in the LDAP view is thus a possibility and actually a good practice: the mere membership of a group will decide on users synchronization.

Currently, warnings & above levels seem to be seen as "important logs" by the Monolog handler:
https://github.com/matomo-org/matomo/blob/bd9aa9db1a95e6f1ef74b45e3723849fab2f292c/plugins/Monolog/Handler/FailureLogMessageDetector.php#L24
A missing password from LDAP generates a warning:
https://github.com/matomo-org/plugin-LoginLdap/blob/aea78502d4f37ef89676bff8dedf18adafadc940/LdapInterop/UserMapper.php#L158
The consequence of logs being seen as important is the CLI console then exits with an unsuccessful exit status.

[PSR-3](https://www.php-fig.org/psr/psr-3/) states this about warnings:
> **Normal** but significant events.

Would that mean the Monolog handler is wrong as exiting unsuccessfully?
If so, that would mean the issue lies in the Matomo backbone and not in this plugin, but has a bigger reach.

**Comment by imrejonk** [comment]
> As [plugin-LoginLdap/LdapInterop/UserMapper.php](https://github.com/matomo-org/plugin-LoginLdap/blob/aea78502d4f37ef89676bff8dedf18adafadc940/LdapInterop/UserMapper.php#L145) Line 145 in [aea7850](https://github.com/matomo-org/plugin-LoginLdap/commit/aea78502d4f37ef89676bff8dedf18adafadc940) points it out, passwords from LDAP are not used in Matomo.

Well, they are used to generate the user's [token_auth](https://matomo.org/faq/general/faq_114/). See the next line:
https://github.com/matomo-org/plugin-LoginLdap/blob/aea78502d4f37ef89676bff8dedf18adafadc940/LdapInterop/UserMapper.php#L144-L147

> [PSR-3](https://www.php-fig.org/psr/psr-3/) states this about warnings:
> > Normal but significant events.

That is incorrect, it describes warnings as "exceptional occurrences that are not errors". The "normal but significant events" description is given to notices.

My LDAP server also doesn't expose userPassword attributes to the LDAP user Matomo binds as. I too consider this good practice. However, since LoginLdap [4.5.2](https://github.com/matomo-org/plugin-LoginLdap/releases/tag/4.5.2), the user passwords (stored hashed in the `matomo_user` database table) are now updated on every login, meaning that the password is set to a random value each time the user logs in. The warning is also flashed very briefly on login:

![Screenshot from 2022-09-13 09-31-25](https://user-images.githubusercontent.com/48715395/189851736-e9202675-122b-4868-bbe5-8ce64ca24ffa.png)

I think the `warning` log level is suitable here. My solution for preventing synchronization in the first place (I don't need synchronization, I'm using LDAP for authentication only) is to set `synchronize_users_after_login = 0`.

**Comment by d19dotca** [comment]
I'm seeing this same issue every time I login, it's quite annoying. Doesn't seem to affect anything other than the annoyance for users logging into my self-hosted Matomo instance. Would love to resolve this somehow.

**Comment by AltamashShaikh** [comment]
@d19dotca Can you update this [line](https://github.com/matomo-org/plugin-LoginLdap/blob/4.x-dev/LdapInterop/UserMapper.php#L136..L140) on your server to below code and check if the warning is gone
```
$this->logger->debug("UserMapper::{func}: Could not find LDAP password for user '{user}', generating random one.",
                array(
                    'func' => __FUNCTION__,
                    'user' => @$ldapUser[$this->ldapUserIdField]
                ));
```

**Comment by d19dotca** [comment]
Forgive my ignorance @AltamashShaikh but where would I place that code specifically? Which file needs that one?

**Comment by AltamashShaikh** [comment]
@d19dotca 
There will be a file called `UserMapper.php` in `/path/to/your/matomo/plugins/LoginLdap/LdapInterop/UserMapper.php`
You need to search for word `warning` which will look something like this `$this->logger->warning` just replace the `warning` word with `debug`

**Comment by brgsousa** [comment]
> @d19dotca Can you update this [line](https://github.com/matomo-org/plugin-LoginLdap/blob/4.x-dev/LdapInterop/UserMapper.php#L136..L140) on your server to below code and check if the warning is gone
> 
> ```
> $this->logger->debug("UserMapper::{func}: Could not find LDAP password for user '{user}', generating random one.",
>                 array(
>                     'func' => __FUNCTION__,
>                     'user' => @$ldapUser[$this->ldapUserIdField]
>                 ));
> ```

I fixed my code using your code.
I am using version 4.5.5 , my suggestion is to include that 'fix' in a future release.

**Comment by AltamashShaikh** [comment]
@brgsousa Thanks for checking.
Created : https://github.com/matomo-org/plugin-LoginLdap/pull/314 an once merged we can release a new version during our release cycle

**Comment by AltamashShaikh** [comment]
@all Just update the plugin to `4.5.6` version of the plugin and this should be fixed.
