### ISSUE TITLE
seems "Using LDAP for authentication only" still stores password in DB

### ISSUE THREAD

**Issue by mhow2** [piwik/plugin-LoginLdap#212]
Matomo v3.12.0
LDAP plugin v4.0.8

in https://plugins.matomo.org/LoginLdap, with the default setup, it is mentioned that 

> (...) the user's password is never stored in Matomo's DB

However, after checking I'm well under the default setup use-case (`Use LDAP for authentication` enabled, `Use Web Server Auth` disabled), authenticating with a new user adds a record in table `matomo_user` with a `password` hash.

Am I missing something ?

**Comment by diosmosis** [comment]
The matomo API requires something be stored in the password field, so LoginLdap will use a dummy value. If "Synchronize Users After Successful Login" is checked, then when logging in this value is updated w/ the user's real password (what the user actually enters on the screen.) Otherwise, it will always have the dummy value.

**Comment by mhow2** [comment]
Thank you for the answer @diosmosis, what's exactly a _dummy_ value ? I just want to make sure it cannot be a "working" password.

**Comment by diosmosis** [comment]
Currently it is an entirely random value or a hash of the LDAP hash of the password if that field is configured by the LDAP server to be returned. Note: that is before `password_hash()` is called on the value.

**Comment by diosmosis** [comment]
Markin
