### ISSUE TITLE
Can't login, if CN contains umlaut

### ISSUE THREAD

**Issue by madoe** [piwik/plugin-LoginLdap#86]
I set up LDAP-Plugin to connect to a 2008R2 ActiveDirectory. I chose sAMAccountName as search field. This is working for most of my users. Unfortunately not for me, probably because my CN contains an umlaut: "Döring, Markus".
I receive the error message: "Error: Wrong Username and password combination."

**Comment by diosmosis** [comment]
If you set the "User ID Field" to sAMAccountName, then login will fail if the sAMAccountName field contains a umlaut (due to this core bug: https://github.com/piwik/piwik/issues/7114). If it's only the CN that contains an umlaut, then you should be able to login.

If your sAMAccountName field has no special characters, then it's not working for another reason. In this case, you might be able to get more information by executing the following console command: `/path/to/php /path/to/piwik/console loginldap:synchronize-users --login="Your sAMAccountName" -vvv`. Replace 'Your sAMAccountName' w/ the appropriate value.

**Comment by madoe** [comment]
Thanks for your response. Indeed the error had nothing to do with the umlaut. Actually I used my e-mail address already for the admin account, so my regular user account could not synchronize correctly.
The console command you mentiond helped sorting this out.
